apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpa4webswing
  labels:
    app: hpa4webswing
spec:
  revisionHistoryLimit: 4 # limit our previous replicasets to four revisions
  replicas: 1 # will be set by the deploy script
  template:
    metadata:
      labels:
        app: hpa4webswing
    spec:
      containers:
      - name: hpa
        image: hpa/hpa:1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
