apiVersion: v1
kind: Service
metadata:
  name: my-app
  annotations:
    # See https://kubernetes.io/docs/tutorials/services/source-ip/
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: my-app
